### ISSUE TITLE
You can't use this version of the application with this version of macOS

### ISSUE THREAD

**Issue by lochstar** [buzsh/SwiftDiffusion#80]
I get an error when trying to launch. I am on macOS 14.1.1.

What version is it compatible with?

**Comment by buzsh** [comment]
Hey @lochstar,

My bad, I forgot to set the deployment target back to 14 for prod before release. You can get the [latest build here](https://github.com/buzsh/SwiftDiffusion/releases/download/v0.1-beta.0/SwiftDiffusion.app.zip) which should only require macOS 14.0 and above.
